---
- name: Register keycloak as a service
  become: yes
  template:
    src: "keycloak.service.j2"
    dest: /etc/systemd/system/keycloak.service
    mode: u=rw,g=r,o=r

- name: Enable keycloak service
  become: yes
  shell: "systemctl enable keycloak.service"

- name: Reload systemctl
  become: yes
  shell: "systemctl daemon-reload"